import {products,prices,mixes,resources,evaluate,status} from './model.js';
import './case-study.css';
const $=s=>document.querySelector(s);
const fmt=v=>new Intl.NumberFormat('es-PE',{maximumFractionDigits:2}).format(v);
export const explanations={
 variables:'Representan la cantidad exacta de unidades a producir de cada tipo de Maki y Ramen al día. Deben ser números enteros positivos.',
 objective:'Busca el mayor ingreso total sumando el precio de venta de cada producto por las unidades producidas. Es la meta financiera del negocio.',
 inventory:'Asegura que la receta combinada de toda la producción no consuma más inventario del que hay disponible hoy.',
 demand:'Obliga al modelo a producir una cantidad mínima de los productos estrella para satisfacer a la clientela habitual.',
 eficaz:'Es un resultado 100% matemático. Exprime cada centavo enfocándose solo en los productos más rentables, aunque eso signifique dejar a clientes sin sus platos favoritos de menor margen.',
 eficiente:'Añade reglas de negocio al cálculo. Acepta ganar ligeramente menos dinero total a cambio de ofrecer un menú completo, cuidando la imagen de marca y la fidelidad del cliente.'
};
const levels=[['Bajo','⚪','< 50%','El inventario sobra excesivamente. Capital inmovilizado.'],['Medio','🟡','≥ 50% y < 80%','Nivel de consumo saludable y manejable.'],['Alto','🟢','≥ 80% y < 95%','Recurso aprovechado casi al máximo, requiere atención.'],['Crítico','🔴','≥ 95%','Cuello de botella absoluto. Este recurso frena el crecimiento de ingresos.']];
export function recommendation(r){const s=status(r);if(s==='Excedido')return ['Replanificar',`Excede el límite en ${fmt(r.used-r.cap)} ${r.unit}. Reoptimizar antes de ejecutar.`];if(s==='Crítico')return ['Recomienda aumentar',r.name==='Tiempo'?'Evaluar la contratación de un ayudante de cocina.':r.name==='Arroz'?'Comprar un saco adicional diario para cubrir la capacidad real de venta.':'Evaluar capacidad adicional y su costo.'];if(s==='Alto')return ['Revisar','Stock en el límite seguro, vigilar mermas.'];if(s==='Bajo')return ['Se recomienda reducir','Comprar envases más pequeños para evitar el vencimiento del producto.'];return ['Mantener','El ritmo de compra actual es el adecuado.'];}
let activeMode='eficaz',activeLimit=500,trial=[...mixes.eficaz];
function explanationCard(title,text,note=''){return `<article class="reading-card"><h3>${title}</h3><p>${text}</p>${note?`<small>${note}</small>`:''}</article>`;}
export function setupCaseStudy(){
 $('.hero-copy').insertAdjacentHTML('beforeend','<div class="case-intro"><span>EL RETO DEL RESTAURANTE</span><p>Distribuir insumos y minutos entre cinco makis y dos ramen. Producción cuida la capacidad; Comercial busca ingresos y una carta completa.</p></div>');
 $('#modelo .section-inner').insertAdjacentHTML('beforeend',`<div class="study-heading"><span>LECTURA DEL MODELO</span><h3>De la fórmula a la decisión diaria</h3><p>Las interpretaciones también están aquí, sin necesidad de pasar el cursor.</p></div><div class="reading-grid">${explanationCard('01 · ¿Qué decidimos?',explanations.variables,'Precisión matemática: son enteros no negativos. El cero está permitido; por ejemplo, California y Tokyo Roll tienen cero unidades en la mezcla eficaz.')}${explanationCard('02 · ¿Qué maximizamos?',explanations.objective,'Z mide ingresos, no utilidad. No se proporcionaron costos unitarios ni márgenes.')}${explanationCard('03 · ¿Qué limita la receta?',explanations.inventory,'Ejemplo: 22 makis × 250 g = 5,500 g de arroz; se consume toda la disponibilidad.')}${explanationCard('04 · ¿Qué limita la cocina?','<span id="explicit-time"></span>','Capacidad del caso: 500 minutos de cocina por día.')}${explanationCard('05 · ¿Qué debemos ofrecer?',explanations.demand,'Acevichado y Furai: mínimo 5 unidades/día. Ramen Especial: mínimo 3 unidades/día.')}</div>`);
 $('#comparativa .section-inner').insertAdjacentHTML('beforeend',`<div class="study-heading"><span>DOS CRITERIOS, UNA DECISIÓN</span><h3>¿Qué gana y qué cede cada área?</h3></div><div class="reading-grid two"><article class="reading-card mode-reading" data-reading="eficaz"><h3>Solución Eficaz · Ingreso</h3><p>${explanations.eficaz}</p><small>En este caso «rentables» se refiere al ingreso con recursos limitados. No hay datos para comparar margen. La mezcla eficaz no ofrece California, Tokyo Roll ni Ramen Clásico.</small></article><article class="reading-card mode-reading" data-reading="eficiente"><h3>Solución Eficiente · Variedad</h3><p>${explanations.eficiente}</p><small>El acuerdo aportado ofrece los siete productos. No se ha demostrado que sea el óptimo entre todas las mezclas con variedad completa.</small></article></div><div class="metric-ribbon"><div><b>S/82</b><span>ingreso diario que se cede</span></div><div><b>7.85%</b><span>reducción frente a S/1,045</span></div><div><b>+3</b><span>productos presentes en carta</span></div><div><b>+5</b><span>unidades: de 37 a 42</span></div></div><div class="study-heading"><span>DESCOMPOSICIÓN DE Z</span><h3>¿Qué aporta cada plato al ingreso?</h3></div><div class="table-scroll"><table class="case-table"><thead><tr><th>Producto</th><th>Precio</th><th>Eficaz · unid.</th><th>Acuerdo · unid.</th><th>Aporte seleccionado</th></tr></thead><tbody id="income-breakdown"></tbody></table></div><div class="lab"><div class="study-heading"><span>LABORATORIO INTERACTIVO</span><h3>Diseña tu propia mezcla</h3><p>Ajusta cantidades y observa ingresos, capacidad y demanda mínima. Esta simulación evalúa factibilidad; no ejecuta Solver.</p></div><div class="lab-toolbar"><button id="trial-copy">Cargar solución seleccionada</button><button id="trial-add">Probar +1 Maki Salmón</button><span id="trial-limit"></span></div><div class="trial-inputs">${products.map((p,i)=>`<label>${p}<input type="number" min="0" max="100" step="1" value="${trial[i]}" data-product="${i}" aria-label="Simular cantidad de ${p}"></label>`).join('')}</div><div id="trial-results" aria-live="polite"></div></div>`);
 $('#recursos .section-inner').insertAdjacentHTML('beforeend',`<div class="study-heading"><span>GUÍA DE LECTURA</span><h3>Estado, interpretación y evidencia</h3></div><div class="reading-grid level-readings">${levels.map(([name,icon,range,text])=>explanationCard(`${icon} ${name} · ${range}`,text)).join('')}</div><p class="case-caveat">Estas son las interpretaciones solicitadas. Un uso bajo no demuestra desperdicio o capital inmovilizado sin costos y vida útil. Un uso ≥95% es una alerta; no prueba que el recurso sea una restricción activa ni que comprar más aumente ingresos.</p><div class="table-scroll"><table class="case-table"><thead><tr><th>Recurso</th><th>Holgura / exceso</th><th>Acción propuesta</th><th>Interpretación explícita</th></tr></thead><tbody id="recommendations"></tbody></table></div><div class="reading-grid two"><article class="reading-card"><h3>Producción · Capacidad verificable</h3><p>La solución eficaz deja 6 minutos libres; el acuerdo deja 0. Ambas cumplen el límite de 500 minutos del caso.</p><small>Un ayudante debe evaluarse con tiempos reales, coordinación y costo incremental.</small></article><article class="reading-card"><h3>Comercial · Variedad con un costo</h3><p>El acuerdo duplica Acevichado de 5 a 10 unidades e incorpora California, Tokyo Roll y Ramen Clásico. Acepta S/963 frente a S/1,045 para sostener la oferta completa.</p><small>La fidelización es una justificación comercial; su efecto en ventas futuras todavía no está medido.</small></article><article class="reading-card"><h3>Evidencia · Vender más puede exceder el límite</h3><p>Agregar 1 Maki Salmón al eficaz eleva el ingreso de S/1,045 a S/1,075, pero requiere 5,750 g de arroz y 506 minutos: excede 250 g y 6 minutos respecto a la base.</p><small>No aprobar producción adicional solo por el ingreso. El simulador permite comprobar este caso.</small></article><article class="reading-card"><h3>Acuerdo y recomendaciones</h3><p>Respetar recetas, mínimos y recursos; reconocer el costo de la variedad; medir ventas y mermas antes de aumentar compras. Queda en desacuerdo cuánto ingreso ceder por la presencia completa del menú.</p><small>La compra de un saco adicional es una propuesta, no una necesidad demostrada: el acuerdo aún tiene 250 g de holgura y carece de tiempo libre. Se requieren tamaño del saco, costo y demanda de venta.</small></article></div>`);
 document.querySelectorAll('.trial-inputs input').forEach(input=>input.addEventListener('input',()=>{trial[Number(input.dataset.product)]=input.value===''?NaN:Number(input.value);renderTrial();}));
 $('#trial-copy').addEventListener('click',()=>{trial=[...mixes[activeMode]];syncInputs();renderTrial();});
 $('#trial-add').addEventListener('click',()=>{trial=[...mixes[activeMode]];trial[3]++;syncInputs();renderTrial();});
}
function syncInputs(){document.querySelectorAll('.trial-inputs input').forEach((el,i)=>el.value=trial[i]);}
function renderTrial(){
 $('#trial-limit').textContent=`Capacidad: ${activeLimit} min · mínimo Ramen Especial: ${activeLimit===400?5:3}`;
 if(trial.some(v=>!Number.isInteger(v)||v<0||v>100)){$('#trial-results').innerHTML='<p class="trial-invalid">Introduce siete cantidades enteras entre 0 y 100. Un campo vacío no se interpreta como cero.</p>';return;}
 const r=evaluate(trial,activeLimit),minimum=activeLimit===400?5:3;
 const errors=r.usage.filter(v=>v.used>v.cap+1e-8).map(v=>`${v.name}: exceso de ${fmt(v.used-v.cap)} ${v.unit}`);
 [[0,5],[2,5],[5,minimum]].forEach(([i,min])=>{if(trial[i]<min)errors.push(`${products[i]}: faltan ${min-trial[i]} unidades para la demanda mínima`);});
 $('#trial-results').innerHTML=`<div class="trial-kpis"><strong>S/ ${fmt(r.income)}<small>Ingreso simulado</small></strong><strong>${r.units}<small>Unidades</small></strong><strong>${r.variety}/7<small>Variedad</small></strong><strong class="${r.feasible?'trial-valid':'trial-invalid'}">${r.feasible?'Factible':'No factible'}<small>Con las restricciones seleccionadas</small></strong></div>${errors.length?`<ul class="trial-errors">${errors.map(e=>`<li>${e}</li>`).join('')}</ul>`:'<p class="trial-valid">Cumple inventario, tiempo, no negatividad, integridad y demandas mínimas. Factible no implica óptima.</p>'}<div class="trial-resource-list">${r.usage.map(v=>`<span class="${v.used>v.cap?'trial-invalid':''}">${v.name}<b>${fmt(v.used)} / ${fmt(v.cap)} ${v.unit}</b></span>`).join('')}</div>`;
}
export function refreshCaseStudy(mode,limit){
 activeMode=mode;activeLimit=limit;
 const time=`El tiempo total de cocina requerido no puede superar los ${limit} minutos operativos del día.`;
 const mapping=[['#modelo .formula-card',explanations.variables],['.objective',explanations.objective],['.ingredients',explanations.inventory],['#time-formula',time],['#demand-formula',explanations.demand]];
 for(const [selector,text] of mapping){const el=$(selector);el.dataset.tip=text;el.tabIndex=0;if(selector.includes('formula')&&el.parentElement.classList.contains('formula-card'))el.parentElement.dataset.tip=text;}
 document.querySelectorAll('.ingredient').forEach(el=>el.dataset.tip=explanations.inventory);
 $('#explicit-time').textContent=time;
 document.querySelectorAll('[data-mode]').forEach(el=>el.dataset.tip=explanations[el.dataset.mode]);
 $('#comparativa .info').dataset.tip=explanations[mode];
 document.querySelectorAll('.legend span').forEach((el,i)=>el.dataset.tip=levels[i][3]);
 document.querySelectorAll('[data-reading]').forEach(el=>el.classList.toggle('selected-reading',el.dataset.reading===mode));
 $('#income-breakdown').innerHTML=products.map((p,i)=>`<tr><th>${p}</th><td>S/ ${prices[i]}</td><td>${mixes.eficaz[i]}</td><td>${mixes.eficiente[i]}</td><td><div class="contribution"><i style="width:${mixes[mode][i]*prices[i]/450*100}%"></i><span>S/ ${mixes[mode][i]*prices[i]}</span></div></td></tr>`).join('');
 $('#recommendations').innerHTML=evaluate(mixes[mode],limit).usage.map(r=>{const [label,text]=recommendation(r),free=r.cap-r.used;return `<tr><th>${r.name}</th><td class="${free<0?'trial-invalid':''}">${fmt(Math.abs(free))} ${r.unit} ${free<0?'de exceso':'libres'}</td><td>${label}</td><td>${text}</td></tr>`;}).join('');
 renderTrial();
}
