import {products} from './model.js';
export function prepareExposition(){
 const $=s=>document.querySelector(s);
 $('.limit-control').replaceWith(Object.assign(document.createElement('span'),{className:'pill',textContent:'Capacidad diaria: 500 min · Ramen Especial ≥ 3'}));
 $('#modelo .model-side .data-note').textContent='Modelo del caso: 500 minutos por día. Demandas mínimas: 5 Acevichado, 5 Furai y 3 Ramen Especial. Todas las cantidades son enteras no negativas.';
 $('.edition').replaceWith(Object.assign(document.createElement('a'),{className:'excel-link',href:'/Excel/InvOperativa_FINAL.xlsx',textContent:'↓ Abrir Excel del caso',download:'InvOperativa_FINAL.xlsx'}));
 const nav=document.createElement('nav');nav.className='rubric-nav';nav.setAttribute('aria-label','Rúbrica de exposición');nav.innerHTML='<a href="#inicio">Descripción <b>25%</b></a><a href="#modelo">Modelo <b>25%</b></a><a href="#acta">Acta de Enfoque <b>50%</b></a>';document.body.append(nav);
 $('#inicio .hero-copy').insertAdjacentHTML('beforeend','<article class="exposition-context"><b>1. DESCRIPCIÓN · 25%</b><p>Makis Yarimashita es un restaurante nikkei que decide su producción diaria de cinco variedades de maki y dos ramen. Dispone de inventario limitado de ocho insumos y 500 minutos de cocina. Debe satisfacer las demandas mínimas de productos de mayor rotación.</p><p>El problema consiste en elegir una mezcla que maximice los ingresos diarios por ventas. Se supone que toda la producción se vende al precio indicado y que las recetas son constantes. El acuerdo comercial añade el interés por ofrecer toda la carta.</p></article>');
 $('#modelo .eyebrow').textContent='2. MODELO MATEMÁTICO · 25%';
 $('#modelo .section-inner').insertAdjacentHTML('beforeend',`<div class="study-heading"><span>VARIABLES Y SISTEMA DE UNIDADES</span><h3>¿Qué representa cada decisión?</h3></div><div class="table-scroll"><table class="case-table"><thead><tr><th>Variable</th><th>Definición</th><th>Unidad</th><th>Dominio</th></tr></thead><tbody>${products.map((p,i)=>`<tr><th>x${i+1}</th><td>Cantidad de ${p} a producir al día</td><td>unidades/día</td><td>Entero ≥ 0</td></tr>`).join('')}</tbody></table></div>`);
 $('#slides').insertAdjacentHTML('beforeend',`<section id="acta" aria-labelledby="acta-title"><div class="section-inner"><p class="eyebrow">3. ACTA DE ENFOQUE · 50% DE LA EVALUACIÓN</p><h2 id="acta-title">Producción <em>× Comercial</em></h2><p class="section-desc">Acta académica del caso · decisiones sustentadas en las mezclas aportadas y sus recursos.</p><div class="acta-verdict"><span>ACUERDO PROPUESTO PARA LA JORNADA</span><h3>Ofrecer toda la carta con S/963 diarios</h3><p>10 Acevichado · 1 California · 5 Furai · 4 Salmón · 1 Tokyo Roll · 9 Ramen Especial · 12 Ramen Clásico.</p><b>42 unidades · 7 productos · 5,250 g de arroz · 500 minutos</b></div><div class="reading-grid two">
 <article class="reading-card"><h3>01 · Modelo Solver – IA</h3><p>Maximizar Z = Σ precio × cantidad, cambiando x₁…x₇. En Solver: Simplex LP para la estructura lineal, restricciones de inventario ≤ disponible, mínimos ≥ demanda y variables enteras no negativas.</p><p>Referencia eficaz: (5, 0, 5, 12, 0, 15, 0), Z = S/1,045. La IA verifica consumos, interpreta el resultado y contrasta escenarios.</p><small>El valor óptimo entero se verificó por enumeración y dominancia. La web evalúa las mezclas; no ejecuta el complemento Solver. El Excel es el soporte del trabajo.</small></article>
 <article class="reading-card"><h3>02 · Postura de Producción</h3><p>Exigir una mezcla factible, respetar recetas y mínimos, y controlar los insumos antes de cocinar. La solución eficaz usa 494 de 500 minutos y todo el arroz; el acuerdo usa 500 minutos y deja 250 g de arroz.</p><small>La postura prioriza la viabilidad: el acuerdo no deja margen de tiempo para incidencias.</small></article>
 <article class="reading-card"><h3>03 · Postura Comercial</h3><p>Ofrecer los siete productos y aumentar Acevichado de 5 a 10 unidades. Aceptar S/82 menos de ingreso diario (7.85%) a cambio de variedad completa y atención a preferencias de clientes.</p><small>El efecto de la variedad en fidelización y ventas futuras se debe medir; no está cuantificado en el modelo.</small></article>
 <article class="reading-card"><h3>04 · Evidencia: mejorar el ingreso excediendo un límite</h3><p>Agregar un Maki Salmón a la mezcla eficaz aumenta Z de S/1,045 a S/1,075. Sin embargo, consume 5,750 g de arroz y 506 minutos: supera la capacidad en 250 g y 6 minutos.</p><small>Decisión: rechazar esa mezcla con los recursos actuales. Antes de ampliar capacidad, comparar ingreso incremental de S/30 con costos incrementales y demanda. No se puede afirmar mejora del margen sin datos de costos.</small><a class="acta-jump" href="#comparativa">Comprobar en el simulador ↗</a></article>
 <article class="reading-card"><h3>05 · Puntos de acuerdo</h3><ul><li>Adoptar la mezcla comercial aportada para ofrecer toda la carta.</li><li>Aceptar el costo de oportunidad de S/82 diarios.</li><li>Respetar 500 minutos, recetas y demandas mínimas.</li><li>Confirmar inventarios antes de ejecutar y registrar ventas y mermas.</li></ul></article>
 <article class="reading-card"><h3>06 · Puntos en desacuerdo</h3><ul><li>Priorizar el ingreso máximo frente a mantener los siete productos.</li><li>Operar sin holgura de tiempo frente a reservar capacidad para imprevistos.</li><li>Aumentar compras o personal antes de demostrar demanda y retorno.</li></ul><small>Son tensiones del análisis académico; no representan una reunión real documentada.</small></article>
 <article class="reading-card"><h3>07 · Recomendaciones</h3><ul><li>Incorporar costos por producto para optimizar utilidad y margen.</li><li>Registrar tiempos reales y evaluar apoyo de cocina.</li><li>No comprar arroz adicional sin revisar la restricción de tiempo.</li><li>Medir ventas por producto antes de fijar nuevos mínimos comerciales.</li><li>Reoptimizar ante cambios de precios, demanda o recursos.</li></ul></article>
 <article class="reading-card"><h3>Conclusión para la exposición</h3><p>La solución eficaz maximiza ingresos con cuatro productos. El acuerdo entrega variedad completa y cumple los límites, pero utiliza todo el tiempo. La decisión comercial tiene un costo cuantificable y requiere disciplina operativa.</p><a class="acta-jump" href="/Excel/InvOperativa_FINAL.xlsx" download="InvOperativa_FINAL.xlsx">Abrir Excel de respaldo ↗</a><small>El navegador descarga el archivo; ábrelo desde Descargas con Excel. La apertura automática depende de la configuración del equipo.</small></article>
 </div></div></section>`);
 $('.progress>span:last-child').textContent='05';
 document.querySelectorAll('.rubric-nav a,.acta-jump[href^="#"]').forEach(a=>a.addEventListener('click',e=>{e.preventDefault();const section=$(a.hash);section.scrollTop=0;section.scrollIntoView({behavior:matchMedia('(prefers-reduced-motion: reduce)').matches?'instant':'smooth'});}));
}
