import './style.css';
import {prepareExposition} from './exposition.js';
import 'katex/dist/katex.min.css';
import katex from 'katex';
import * as THREE from 'three';
import {products,mixes,resources,evaluate,status} from './model.js';
import {setupCaseStudy,refreshCaseStudy,recommendation} from './case-study.js';

const $=s=>document.querySelector(s);
prepareExposition();
const sections=[...document.querySelectorAll('main section')];
const reduced=matchMedia('(prefers-reduced-motion: reduce)');
let current=0,mode='eficaz',limit=500,resourceVisible=false,paused=reduced.matches;
const number=new Intl.NumberFormat('es-PE',{maximumFractionDigits:2});
const money=v=>`S/ ${number.format(v)}`;
function math(el,value){katex.render(value,el,{displayMode:true,throwOnError:false,strict:'warn'});}
const staticMath=document.querySelectorAll('[data-math]');
staticMath[0].dataset.math='x_1,\\ldots,x_7\\geq0,\\quad x_i\\in\\mathbb{Z}\\quad[\\mathrm{unidades/día}]';
staticMath[1].dataset.math='\\max Z=22x_1+20x_2+25x_3+30x_4+28x_5+30x_6+15x_7\\quad[\\mathrm{S/ día}]';
staticMath.forEach(el=>math(el,el.dataset.math));
const formulas=[['Salsas','L','0.08x_1+0.04x_2+0.06x_3+0.04x_4+0.07x_5\\le3\\,\\mathrm{L}'],['Arroz','g','250(x_1+x_2+x_3+x_4+x_5)\\le5500\\,\\mathrm{g}'],['Salmón','porciones','x_1+x_4+x_5\\le30\\,\\mathrm{porciones}'],['Langostino','unidades','3(x_1+x_2+x_3+x_4+x_5)\\le70\\,\\mathrm{unidades}'],['Palta','porciones','3(x_1+x_2+x_3+x_4+x_5)\\le100\\,\\mathrm{porciones}'],['Queso crema','porciones','3(x_1+x_2+x_3+x_4+x_5)\\le100\\,\\mathrm{porciones}'],['Fideos','unidades','x_6+x_7\\le30\\,\\mathrm{unidades}'],['Cerdo','porciones','3x_6\\le50\\,\\mathrm{porciones}']];
for(const [name,unit,formula] of formulas){const el=document.createElement('div');el.className='ingredient';el.tabIndex=0;el.dataset.tip=`${name}: el consumo de toda la producción no puede superar el inventario disponible. La unidad de control es ${unit}.`;el.innerHTML=`<span>${name} <small>(${unit})</small></span><div></div>`;math(el.lastChild,formula);$('#formulas').append(el);}
function updateFormulas(){math($('#time-formula'),`10x_1+10x_2+15x_3+12x_4+12x_5+15x_6+10x_7\\le ${limit}\\,\\mathrm{minutos}`);math($('#demand-formula'),`x_1\\ge5\\,\\mathrm{unidades/día},\\quad x_3\\ge5\\,\\mathrm{unidades/día},\\quad x_6\\ge${limit===500?3:5}\\,\\mathrm{unidades/día}`);}
function dish(i){return i<5?`<svg viewBox="0 0 110 100" aria-hidden="true"><ellipse cx="55" cy="83" rx="42" ry="8" fill="#0005"/><path d="M18 39v29c0 29 74 29 74 0V39" fill="#354333"/><ellipse cx="55" cy="39" rx="37" ry="25" fill="#f2e9d8"/><ellipse cx="55" cy="39" rx="22" ry="16" fill="${['#f8895b','#91ad60','#c9994c','#fa7c54','#8ca267'][i]}"/><path d="M40 32l25 14M48 26l23 13" stroke="#ffe2bd" stroke-width="4"/><g fill="#fff9e8"><ellipse cx="26" cy="37" rx="3" ry="6"/><ellipse cx="76" cy="26" rx="5" ry="2"/><ellipse cx="72" cy="52" rx="3" ry="4"/></g></svg>`:`<svg viewBox="0 0 110 100" aria-hidden="true"><path d="M12 40q4 49 43 49t43-49" fill="${i===5?'#aa482e':'#577269'}"/><ellipse cx="55" cy="40" rx="43" ry="18" fill="#d8b278"/><path d="M22 37q18-19 32 1t33 0M22 45q18-17 32 0t33 0" fill="none" stroke="#fbe0a1" stroke-width="4"/><ellipse cx="64" cy="34" rx="12" ry="10" fill="#fdf0d6"/><circle cx="64" cy="34" r="5" fill="#efa539"/><path d="M24 29l22 6M28 24l19 6" stroke="#6c9449" stroke-width="5"/><path d="M38 16q-6-7 1-12M56 15q-6-7 1-12" stroke="#e7d2b7" opacity=".5" fill="none"/></svg>`;}
const colors={Bajo:'#c3b9ad',Medio:'#d8b458',Alto:'#90b981','Crítico':'#f57d62',Excedido:'#ff5266'};
function action(r){return recommendation(r);}
function render(){const x=mixes[mode],result=evaluate(x,limit);$('#mode-title').textContent=mode==='eficaz'?'Solución eficaz · Matemática pura':'Solución eficiente · Acuerdo comercial';$('#mode-description').textContent=mode==='eficaz'?'Prioriza ingresos con cuatro productos. Consume todo el arroz y 494 minutos de cocina.':'Ofrece los siete productos de la carta. Acepta un menor ingreso y utiliza 500 minutos de cocina.';$('#income').textContent=money(result.income);$('#difference').textContent=mode==='eficaz'?'Máximo entero para el escenario de 500 min':'−S/ 82 · −7.85% frente a eficaz';$('#plates').innerHTML=x.map((n,i)=>`<button class="plate ${n===0?'empty':''}" data-tip="${products[i]}: ${n} unidades diarias en la solución ${mode}." aria-label="${products[i]}, ${n} unidades">${dish(i)}<span class="plate-name">${products[i]}</span><b>${n.toString().padStart(2,'0')}</b><small>UNIDADES / DÍA</small></button>`).join('');$('#units').textContent=`${result.units} unidades diarias`;$('#variety').textContent=`${result.variety} de 7 productos disponibles`;$('#feasibility').className=result.feasible?'':'bad';$('#feasibility').textContent=result.feasible?`Factible · capacidad ${limit} min`:`No factible · excede ${result.usage.at(-1).used-limit} min`;$('#resource-mode').textContent=`${mode==='eficaz'?'Eficaz':'Eficiente'} / ${limit} minutos`;$('#resources').innerHTML=result.usage.map(r=>{const p=r.used/r.cap*100,s=status(r),[label,tip]=action(r);return `<article class="resource" style="--bar-color:${colors[s]}"><div class="resource-top"><span>${r.name}</span><strong>${number.format(p)}%</strong></div><div class="track" role="progressbar" aria-label="Uso de ${r.name}" aria-valuenow="${Math.min(100,p)}" aria-valuemin="0" aria-valuemax="100" aria-valuetext="${number.format(p)} por ciento; ${s}"><div class="bar" data-width="${Math.min(100,p)}"></div></div><div class="resource-bottom"><span>${number.format(r.used)} / ${number.format(r.cap)} ${r.unit}<br>${s}</span><button class="action" data-tip="${tip}">${label}</button></div></article>`;}).join('');if(resourceVisible)animateBars();document.querySelectorAll('[data-mode]').forEach(b=>b.setAttribute('aria-pressed',String(b.dataset.mode===mode)));}
function animateBars(){requestAnimationFrame(()=>requestAnimationFrame(()=>document.querySelectorAll('.bar').forEach(b=>b.style.width=`${b.dataset.width}%`)));}
// Keep the expanded analysis synchronized with both presentation controls.
document.querySelectorAll('[data-mode]').forEach(b=>b.addEventListener('click',()=>queueMicrotask(()=>refreshCaseStudy(b.dataset.mode,limit))));

document.querySelectorAll('[data-mode]').forEach(b=>b.addEventListener('click',()=>{mode=b.dataset.mode;render();}));
function go(i){sections[Math.max(0,Math.min(sections.length-1,i))].scrollIntoView({behavior:reduced.matches?'instant':'smooth',block:'start'});}
$('#prev').addEventListener('click',()=>go(current-1));$('#next').addEventListener('click',()=>go(current+1));$('#start').addEventListener('click',()=>go(1));
document.addEventListener('keydown',e=>{if(e.key==='Escape')hideTip();if(['INPUT','SELECT','TEXTAREA','BUTTON'].includes(document.activeElement.tagName))return;if(e.key==='PageDown'){e.preventDefault();go(current+1);}if(e.key==='PageUp'){e.preventDefault();go(current-1);}});
const tip=$('#tooltip');let tipTarget=null;
function hideTip(){if(tipTarget)tipTarget.removeAttribute('aria-describedby');tipTarget=null;tip.hidden=true;}
function showTip(target){if(!target)return;hideTip();tipTarget=target;tip.textContent=target.dataset.tip;tip.hidden=false;target.setAttribute('aria-describedby','tooltip');const r=target.getBoundingClientRect(),t=tip.getBoundingClientRect();tip.style.left=`${Math.max(12,Math.min(innerWidth-t.width-12,r.left+r.width/2-t.width/2))}px`;tip.style.top=`${r.top>t.height+16?r.top-t.height-10:Math.min(innerHeight-t.height-12,r.bottom+10)}px`;}
document.addEventListener('pointerover',e=>{const el=e.target.closest('[data-tip]');if(el&&el!==tipTarget)showTip(el);});document.addEventListener('pointerout',e=>{if(tipTarget&&!tipTarget.contains(e.relatedTarget))hideTip();});document.addEventListener('focusin',e=>showTip(e.target.closest('[data-tip]')));document.addEventListener('focusout',hideTip);document.addEventListener('click',e=>{const el=e.target.closest('[data-tip]');if(el)showTip(el);else hideTip();});$('#slides').addEventListener('scroll',hideTip,{passive:true});sections.forEach(s=>s.addEventListener('scroll',hideTip,{passive:true}));

// Fixed Three.js scene; rendering remains local and degrades gracefully without WebGL.
let renderer,scene,camera,particles,frame,previous=performance.now();const target=new THREE.Vector3(0,0,8);const cameras=[[0,0,8],[1.2,.4,6],[-1,-.3,7],[.5,1,5.5],[0,.5,7]];
try{renderer=new THREE.WebGLRenderer({canvas:$('#universe'),alpha:true,antialias:true,powerPreference:'low-power'});renderer.setPixelRatio(Math.min(devicePixelRatio,1.5));renderer.setSize(innerWidth,innerHeight);scene=new THREE.Scene();camera=new THREE.PerspectiveCamera(55,innerWidth/innerHeight,.1,100);camera.position.copy(target);const count=650,positions=new Float32Array(count*3),colorsArray=new Float32Array(count*3);for(let i=0;i<count;i++){positions.set([(Math.random()-.5)*22,(Math.random()-.5)*16,(Math.random()-.5)*12],i*3);colorsArray.set([1,.18+Math.random()*.35,.06+Math.random()*.12],i*3);}const geometry=new THREE.BufferGeometry();geometry.setAttribute('position',new THREE.BufferAttribute(positions,3));geometry.setAttribute('color',new THREE.BufferAttribute(colorsArray,3));const sprite=document.createElement('canvas');sprite.width=sprite.height=32;const ctx=sprite.getContext('2d'),gradient=ctx.createRadialGradient(16,16,0,16,16,16);gradient.addColorStop(0,'white');gradient.addColorStop(.25,'#ffffffaa');gradient.addColorStop(1,'#ffffff00');ctx.fillStyle=gradient;ctx.fillRect(0,0,32,32);const material=new THREE.PointsMaterial({size:.055,map:new THREE.CanvasTexture(sprite),vertexColors:true,transparent:true,opacity:.75,depthWrite:false,blending:THREE.AdditiveBlending});particles=new THREE.Points(geometry,material);scene.add(particles);renderer.render(scene,camera);}catch(error){$('#universe').hidden=true;console.warn('Fondo 3D no disponible; se conserva el fondo CSS.',error.message);}
function tick(now){frame=null;if(!renderer||paused||document.hidden)return;const delta=Math.min((now-previous)/1000,.05);previous=now;particles.rotation.y+=delta*.018;particles.rotation.x+=delta*.004;camera.position.lerp(target,1-Math.exp(-delta*2));camera.lookAt(0,0,0);renderer.render(scene,camera);frame=requestAnimationFrame(tick);}
function startAnimation(){if(renderer&&!paused&&!document.hidden&&frame==null){previous=performance.now();frame=requestAnimationFrame(tick);}}
function motionLabel(){$('#motion').textContent=paused?'Animar fondo':'Pausar fondo';$('#motion').setAttribute('aria-pressed',String(paused));}
$('#motion').addEventListener('click',()=>{paused=!paused;motionLabel();startAnimation();});reduced.addEventListener('change',e=>{paused=e.matches;motionLabel();startAnimation();});document.addEventListener('visibilitychange',startAnimation);window.addEventListener('resize',()=>{hideTip();if(!renderer)return;camera.aspect=innerWidth/innerHeight;camera.updateProjectionMatrix();renderer.setSize(innerWidth,innerHeight);renderer.render(scene,camera);});
const observer=new IntersectionObserver(entries=>{for(const entry of entries){if(entry.isIntersecting&&entry.intersectionRatio>=.55){current=sections.indexOf(entry.target);$('#page').textContent=String(current+1).padStart(2,'0');$('#progress-bar').style.width=`${(current+1)/sections.length*100}%`;$('#prev').disabled=current===0;$('#next').disabled=current===sections.length-1;target.set(...cameras[current]);if(paused&&renderer){camera.position.copy(target);camera.lookAt(0,0,0);renderer.render(scene,camera);}resourceVisible=current===3;if(resourceVisible)animateBars();}}},{root:$('#slides'),threshold:[.55,.8]});sections.forEach(s=>observer.observe(s));
window.addEventListener('pagehide',()=>{if(frame)cancelAnimationFrame(frame);observer.disconnect();if(particles){particles.geometry.dispose();particles.material.map.dispose();particles.material.dispose();}renderer?.dispose();});
updateFormulas();render();setupCaseStudy();refreshCaseStudy(mode,limit);motionLabel();startAnimation();
