import {initPage} from '../main.js';
import {products,prices,baseMix,resources,demand,sensitivityReport,transport} from '../data.js';
import {solveLP} from '../lp.js';
import {lineChart} from '../charts.js';
import {burst} from '../background3d.js';
import {decorateHero} from '../illustrations.js';

const $=(s,r=document)=>r.querySelector(s),fmt=(v,d=2)=>new Intl.NumberFormat('es-PE',{minimumFractionDigits:0,maximumFractionDigits:d}).format(v);
const defaults=()=>({prices:[...prices],caps:resources.map(r=>r.cap),mins:demand.map(d=>d.value)});let state=defaults(),compareBase=false,score=0;
const minIndexes=demand.map(d=>d.index);
function constraintsFor(s=state){return[...resources.map((r,i)=>({a:r.a,b:s.caps[i],sense:'<=',name:r.name})),...s.mins.map((v,i)=>({a:products.map((_,j)=>j===minIndexes[i]?-1:0),b:-v,sense:'<=',name:`Mínimo ${demand[i].label}`}))];}
function solve(s=state){return solveLP({objective:s.prices,constraints:constraintsFor(s)});}
const sameMix=x=>x.every((v,i)=>Math.abs(v-baseMix[i])<.005);
const unitLabels=['unid.','unid.','unid.','unid.','unid.','unid.','unid.'];
decorateHero('sensitivity');
function renderResult(message='Modelo base resuelto.'){const result=solve(),host=$('#sensitivity-result');$('#sensitivity-narrator').textContent=`💡 ¿Qué estás viendo? ${message}`;if(result.estado!=='optimo'){host.innerHTML='<div class="status-line bad">Infactible: los mínimos solicitados superan recursos disponibles.</div>';return result;}
 const used=resources.map((r,i)=>({name:r.name,unit:r.unit,value:r.a.reduce((s,a,j)=>s+a*result.x[j],0),cap:state.caps[i]}));const active=used.filter(r=>r.cap&&Math.abs(r.value/r.cap-1)<.005).map(r=>r.name);const isBase=sameMix(result.x);
 host.innerHTML=`<div class="stat-row"><div class="stat"><b>S/ ${fmt(result.z,3)}</b><span>INGRESO OBJETIVO</span></div><div class="stat"><b>${fmt(result.z-1057,3)}</b><span>CAMBIO VS BASE</span></div><div class="stat"><b>${result.x.filter(v=>v>1e-6).length}/7</b><span>PRODUCTOS EN PLAN</span></div><div class="stat"><b>${active.length||'—'}</b><span>RESTRICCIONES ACTIVAS</span></div></div><div class="status-line ${isBase?'good':'warn'}">${isBase?'Dentro de la mezcla base: cambia el ingreso, se mantiene la base.':'La mezcla cambió frente al plan base. Revisa productos que entran y salen.'}</div><h3 style="margin-top:18px">Producción calculada · unidades/día</h3>${products.map((p,i)=>{const base=baseMix[i],v=result.x[i],d=v-base,chg=Math.abs(d)>1e-6;return `<div class="bar-row"><span>${p}</span><span class="track"><i class="fill" style="width:${Math.min(100,v/20*100)}%"></i>${chg?`<i class="base-dot" style="left:${Math.min(100,base/20*100)}%"></i>`:''}${compareBase&&base>0?`<i class="fill muted" style="width:${Math.min(100,base/20*100)}%;opacity:.45"></i>`:''}</span><b class="prod-val">${fmt(v,3)}${chg?`<small class="prod-delta ${d>0?'up':'down'}">${fmt(base,3)} → ${fmt(v,3)} · ${d>0?'+':''}${fmt(d,3)}</small>`:''}</b></div>`;}).join('')}<div class="pill-row">${used.map(r=>{const pct=r.value/(r.cap||1);const label=pct>=.95?'🔴 Crítico':pct>=.8?'🟢 Alto':pct>=.5?'🟡 Medio':'⚪ Bajo';return `<span class="pill">${r.name}: ${fmt(r.value,2)} / ${fmt(r.cap,2)} ${r.unit} · ${label}</span>`;}).join('')}</div>`;return result;}
function renderControls(){const host=$('#sensitivity-controls');host.innerHTML=`<section class="sensitivity-group"><div class="sensitivity-group-head"><span class="kicker">01 · INGRESOS</span><h3>Precio de venta</h3><p>Modifica el ingreso por unidad y observa cómo cambia la mezcla óptima.</p></div><div class="sensitivity-control-grid">${products.map((p,i)=>`<label class="control sensitivity-control"><span class="control-name">${p}</span><output id="price-value-${i}">S/ ${fmt(state.prices[i],2)}</output><input class="range" type="range" min="${prices[i]*.5}" max="${prices[i]*1.5}" value="${state.prices[i]}" step=".1" data-price="${i}" aria-label="Precio de ${p}"></label>`).join('')}</div></section><section class="sensitivity-group"><div class="sensitivity-group-head"><span class="kicker">02 · CAPACIDAD</span><h3>Recursos disponibles</h3><p>Amplía o reduce los límites diarios de los recursos críticos.</p></div><div class="sensitivity-control-grid"><label class="control sensitivity-control"><span class="control-name">Tiempo de cocina</span><output id="cap-value-8">${fmt(state.caps[8])} min</output><input class="range" type="range" min="300" max="700" value="${state.caps[8]}" data-cap="8" aria-label="Tiempo disponible en minutos"></label><label class="control sensitivity-control"><span class="control-name">Arroz</span><output id="cap-value-1">${fmt(state.caps[1])} g</output><input class="range" type="range" min="4000" max="7000" value="${state.caps[1]}" step="10" data-cap="1" aria-label="Arroz disponible en gramos"></label></div><details class="sensitivity-more"><summary>Mostrar otros recursos</summary><div class="sensitivity-control-grid">${resources.map((r,i)=>[1,8].includes(i)?'':`<label class="control sensitivity-control"><span class="control-name">${r.name} · ${r.unit}</span><output id="cap-value-${i}">${fmt(state.caps[i])} ${r.unit}</output><input class="range" type="range" min="${r.cap*.4}" max="${r.cap*1.5}" value="${state.caps[i]}" step="${r.cap<10?.1:1}" data-cap="${i}" aria-label="Límite de ${r.name} en ${r.unit}"></label>`).join('')}</div></details></section><section class="sensitivity-group"><div class="sensitivity-group-head"><span class="kicker">03 · COMPROMISO COMERCIAL</span><h3>Demandas mínimas</h3><p>Define el mínimo diario que debe producirse de cada producto estrella.</p></div><div class="sensitivity-control-grid">${demand.map((d,i)=>`<label class="control sensitivity-control"><span class="control-name">${d.label}</span><output id="min-value-${i}">${fmt(state.mins[i],2)} unid.</output><input class="range" type="range" min="0" max="20" value="${state.mins[i]}" step=".1" data-min="${i}" aria-label="Demanda mínima de ${d.label} en unidades"></label>`).join('')}</div></section>`;
 host.querySelectorAll('[data-price]').forEach(el=>el.addEventListener('input',()=>{const i=+el.dataset.price;state.prices[i]=+el.value;$('#price-value-'+i).textContent=`S/ ${fmt(el.value,2)}`;renderResult(`Ajustaste ${products[i]} a S/ ${fmt(el.value,2)}; se reoptimizó la mezcla.`);}));
 host.querySelectorAll('[data-cap]').forEach(el=>el.addEventListener('input',()=>{const i=+el.dataset.cap;state.caps[i]=+el.value;$('#cap-value-'+i).textContent=`${fmt(el.value,2)} ${resources[i].unit}`;renderResult(`Cambiaste el límite de ${resources[i].name} a ${fmt(el.value,2)} ${resources[i].unit}.`);}));
 host.querySelectorAll('[data-min]').forEach(el=>el.addEventListener('input',()=>{const i=+el.dataset.min;state.mins[i]=+el.value;$('#min-value-'+i).textContent=`${fmt(el.value,2)} unid.`;renderResult(`El mínimo de ${demand[i].label} ahora es ${fmt(el.value,2)} unidades.`);}));
}
function loadScenario(name,change){state=defaults();change(state);renderControls();const r=renderResult(`Escenario «${name}»: el solver recalculó el modelo.`);$('#scenario-narrator').textContent=r.estado==='optimo'?`${name}: Z = S/ ${fmt(r.z,3)}; solución calculada con la matriz completa.`:'Escenario infactible.';$('#laboratorio').scrollIntoView({behavior:'smooth'});}
function setupScenarios(){const cases=[['Salmón S/ 27',s=>s.prices[3]=27],['Ramen Especial S/ 20',s=>s.prices[5]=20],['Turno +19 min',s=>s.caps[8]=519],['Turno +100 min',s=>s.caps[8]=600],['California S/ 27',s=>s.prices[1]=27],['+1 kg arroz',s=>s.caps[1]=6500]];$('#scenario-buttons').innerHTML=cases.map(([n],i)=>`<button class="button" data-scenario="${i}">${n}</button>`).join('');$('#scenario-buttons').querySelectorAll('button').forEach((b,i)=>b.onclick=()=>loadScenario(cases[i][0],cases[i][1]));$('#reset-sensitivity').onclick=()=>{state=defaults();compareBase=false;$('#toggle-base').setAttribute('aria-pressed','false');renderControls();renderResult('Volvimos a los datos base.');$('#scenario-narrator').textContent='Controles restaurados al caso base.';};$('#toggle-base').onclick=()=>{compareBase=!compareBase;$('#toggle-base').setAttribute('aria-pressed',String(compareBase));renderResult(compareBase?'La solución base se superpone en gris.':'Se ocultó la referencia base.');};}
function setupReportTable(){const rows=sensitivityReport.products;$('#sensitivity-table').innerHTML=rows.map(r=>`<tr><th>${r.name}</th><td>S/ ${fmt(r.coef,2)}</td><td>S/ ${fmt(r.min,2)}</td><td>${r.max===null?'Sin límite':`S/ ${fmt(r.max,2)}`}</td><td>S/ ${fmt(r.reduced,2)}</td></tr>`).join('');}
function setupCurves(){const baseZ=solve(defaults()).z,cases=[{idx:8,min:300,max:700,step:10,range:[314,519],target:'#time-curve',slider:'#curve-time',label:'#time-curve-label',warn:'#time-warning',resV:'#time-resource-value',resD:'#time-resource-delta',zV:'#time-z-value',zD:'#time-z-delta',base:500,unit:'min'},{idx:1,min:4500,max:7000,step:62.5,range:[5104.17,5833.33],target:'#rice-curve',slider:'#curve-rice',label:'#rice-curve-label',warn:'#rice-warning',resV:'#rice-resource-value',resD:'#rice-resource-delta',zV:'#rice-z-value',zD:'#rice-z-delta',base:5500,unit:'g'}];for(const c of cases){const values=[];for(let i=0;i<41;i++){const x=c.min+(c.max-c.min)*i/40,s=defaults();s.caps[c.idx]=x;const r=solve(s);values.push({x,y:r.z});}const draw=x=>{const s=defaults();s.caps[c.idx]=x;const result=solve(s),before=defaults();before.caps[c.idx]=Math.max(c.min,x-1);const after=defaults();after.caps[c.idx]=Math.min(c.max,x+1);const z1=solve(before).z,z2=solve(after).z,slope=(z2-z1)/(Math.min(c.max,x+1)-Math.max(c.min,x-1)||1);$(c.target).innerHTML=lineChart(values,{minX:c.min,maxX:c.max,label:c.unit,validRange:c.range,base:{x:c.base,y:baseZ},marker:{x,y:result.z},color:document.body.classList.contains('transport-page')?'#7dd8c1':'#e7a64c'});const inRange=x>=c.range[0]&&x<=c.range[1],warn=$(c.warn);warn.hidden=inRange;if(!inRange)warn.textContent=`Pasaste el tope ${x<c.range[0]?'inferior':'superior'} (${fmt(c.range[0],2)}–${fmt(c.range[1],2)} ${c.unit}): el precio sombra ya no se sostiene. Otro recurso pasa a ser el cuello de botella y la pendiente de la curva cambia; hay que reoptimizar el modelo.`;$(c.label).textContent=`${fmt(x,2)} ${c.unit} → Z = S/ ${fmt(result.z,3)} · pendiente local ≈ S/ ${fmt(slope,4)} por ${c.unit}.`;const dRes=x-c.base,dZ=result.z-baseZ;$(c.resV).textContent=`${fmt(x,2)} ${c.unit}`;const rd=$(c.resD);rd.textContent=dRes===0?'Caso base':`${dRes>0?'+':''}${fmt(dRes,2)} ${c.unit}`;rd.className='curve-box-delta '+(dRes===0?'base':dRes>0?'up':'down');$(c.zV).textContent=`S/ ${fmt(result.z,3)}`;const zd=$(c.zD);zd.textContent=dZ===0?'Caso base':`${dZ>0?'+':''}S/ ${fmt(dZ,3)}`;zd.className='curve-box-delta '+(dZ===0?'base':dZ>0?'up':'down');};const slider=$(c.slider);slider.addEventListener('input',()=>draw(+slider.value));draw(c.base);}}
function setupFlips(){document.querySelectorAll('.flip').forEach(card=>{const flip=()=>{card.classList.toggle('open');card.setAttribute('aria-pressed',String(card.classList.contains('open')));};card.addEventListener('click',e=>{if(e.target.closest('a'))return;flip();});card.addEventListener('keydown',e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();flip();}});});}
function setupSimulator(){const report=sensitivityReport.products,f2=v=>new Intl.NumberFormat('es-PE',{minimumFractionDigits:2,maximumFractionDigits:2}).format(v),q=s=>document.querySelector(s),pct=(v,a,b)=>(v-a)/(b-a)*100;let idx=1;function render(){const p=report[idx],price=p.coef,lo=price*.5,hi=price*1.5,mult=+q('#sim-slider').value,sim=price*mult,inRange=sim>=p.min-1e-9&&(p.max===null||sim<=p.max+1e-9);q('#sim-products').innerHTML=report.map((r,i)=>`<button class="sim-product ${i===idx?'active':''}" data-idx="${i}">${r.name}<b>S/ ${r.coef}</b></button>`).join('');q('#sim-price').textContent=`S/ ${f2(sim)}`;q('#sim-current').textContent=`S/ ${price}`;q('.sim-slider-scale').innerHTML=`<span>0.5× · S/ ${f2(lo)}</span><span>1× · S/ ${f2(price)}</span><span>1.5× · S/ ${f2(hi)}</span>`;const gs=Math.max(p.min,lo),ge=p.max===null?hi:Math.min(p.max,hi),a=Math.min(price,sim),b=Math.max(price,sim);q('#sim-rangebar').innerHTML=`<div class="sim-zone safe" style="left:${pct(gs,lo,hi)}%;width:${Math.max(0,pct(ge,lo,hi)-pct(gs,lo,hi))}%"></div><div class="sim-zone move ${inRange?'ok':'bad'}" style="left:${pct(a,lo,hi)}%;width:${Math.max(0,pct(b,lo,hi)-pct(a,lo,hi))}%"></div><span class="sim-marker actual" style="left:${pct(price,lo,hi)}%"><i></i>ACTUAL</span><span class="sim-marker sim" style="left:${pct(sim,lo,hi)}%"><i></i>SIMULADO</span>`;const badge=q('#sim-badge');badge.className='sim-badge '+(inRange?'good':'bad');badge.textContent=inRange?'EL PLAN ÓPTIMO SE MANTIENE':'EL PLAN ÓPTIMO CAMBIA · REOPTIMIZAR';q('#sim-row-current').textContent=`S/ ${price}`;const d=sim-price,rd=q('#sim-row-delta');rd.textContent=`${d>0?'+':''}S/ ${f2(d)}`;rd.className='delta '+(d>0?'up':d<0?'down':'');q('#sim-row-reduced').textContent=`${p.reduced<0?'−':''}S/ ${f2(Math.abs(p.reduced))}`;q('#sim-row-units').textContent=p.solution.toFixed(1);q('#sim-expl').textContent=p.solution>1e-9?`Se producen ${p.solution} unidades en el óptimo: su precio cubre el valor de los recursos que consume.`:`Su precio no cubre el valor de los recursos que consume. No se produce: le faltan S/ ${f2(Math.abs(p.reduced))} por unidad.`;q('#sim-caption').textContent=`Rango permisible de ${p.name}: ${p.min>0?`baja hasta S/ ${f2(p.min)} y `:''}${p.max===null?'no tiene tope superior: el plan óptimo se mantiene ante cualquier subida.':`sube hasta S/ ${f2(p.max)}. El plan óptimo se mantiene mientras el precio no supere ese tope.`}`;const np=report.filter(r=>r.solution<=1e-9);q('#sim-nonproduced').textContent=np.length?`${np.map(r=>r.name).join(', ')} no se producen porque su precio no cubre el valor de los recursos que consumen: les faltan ${np.map(r=>`S/ ${f2(Math.abs(r.reduced))}`).join(', ')} respectivamente.`:'Todos los productos participan en el plan óptimo.';}q('#sim-products').addEventListener('click',e=>{const b=e.target.closest('.sim-product');if(!b)return;idx=+b.dataset.idx;q('#sim-slider').value='1';render();});q('#sim-slider').addEventListener('input',render);render();}
function setupQuiz(){const items=[{q:'Te ofrecen 1 kg extra de arroz por S/ 20. ¿Conviene?',correct:'no',a:'No: hasta 333 g aportan cerca de S/ 8; el resto debe reoptimizarse.',fn:s=>s.caps[1]=6500},{q:'Puedes pagar S/ 25 por 15 minutos extra. ¿Conviene?',correct:'yes',a:'Sí bajo el reporte: 15 × S/ 2 = S/ 30 y 15 está dentro de +19 min.',fn:s=>s.caps[8]=515},{q:'Pagar S/ 180 por 100 minutos extra. ¿Conviene?',correct:'no',a:'No se debe multiplicar todo por S/ 2: 100 min excede el rango +19; el modelo da el aumento real.',fn:s=>s.caps[8]=600},{q:'El precio del Salmón baja de S/ 30 a S/ 27. ¿Qué ocurre con el plan óptimo?',options:[{label:'Entra Tokyo Roll y sale el Salmón; Z baja a S/ 1,033.',correct:true},{label:'La mezcla base se mantiene y solo cae el ingreso.',correct:false},{label:'El Salmón sale y el modelo se vuelve infactible.',correct:false}],a:'El mínimo permisible del Salmón es S/ 28. Al bajar a S/ 27, el plan cambia: Tokyo Roll entra con 12 unidades, el Salmón sale y Z = S/ 1,033.',fn:s=>s.prices[3]=27}];$('#quiz').innerHTML=items.map((v,i)=>`<article class="card"><span class="kicker">DECISIÓN ${i+1}</span><h3>${v.q}</h3><div class="button-row">${v.options?v.options.map((o,j)=>`<button class="button opt" data-answer="${i}" data-choice="${j}">${o.label}</button>`).join(''):`<button class="button" data-answer="${i}" data-choice="yes">Sí</button><button class="button" data-answer="${i}" data-choice="no">No</button>`}</div><p id="quiz-answer-${i}" class="narrator" hidden></p><button id="quiz-test-${i}" class="button" hidden>Probarlo en el laboratorio</button></article>`).join('');$('#quiz').querySelectorAll('[data-answer]').forEach(btn=>btn.onclick=()=>{const i=+btn.dataset.answer,item=items[i],p=$(`#quiz-answer-${i}`),correct=item.options?item.options[+btn.dataset.choice].correct:btn.dataset.choice===item.correct;p.hidden=false;p.textContent=`${correct?'✓ Correcto.':'Aún no.'} ${item.a}`;p.classList.toggle('good',correct);p.classList.toggle('warn',!correct);const test=$(`#quiz-test-${i}`);test.hidden=false;test.onclick=()=>loadScenario(item.q,item.fn);if(correct)score++;$('#quiz-score').textContent=`Puntaje: ${score} / 4 · ${correct?'respuesta correcta':'revisa el cálculo'}.`;btn.parentElement.querySelectorAll('button').forEach(b=>b.disabled=true);});}

setupReportTable();setupFlips();renderControls();renderResult('Caso base: X = (5, 0, 5, 12, 0, 15.4, 0), Z = S/ 1,057.');setupScenarios();setupCurves();setupSimulator();setupQuiz();
initPage({palette:[1,.39,.22],count:450,cameras:[[0,0,9],[.5,.2,8],[-.6,.3,7],[.2,-.4,6],[.8,.2,7],[-.4,.5,8],[0,0,9]]});
