import * as THREE from 'three';
const reduce=matchMedia('(prefers-reduced-motion: reduce)');
let active=null;
export function initBackground(canvas,{palette=[1,.6,.25],count=420,cameras=[]}={}){
 let renderer,scene,camera,stars,ornaments,frame=null;const bursts=new Set();const target=new THREE.Vector3(0,0,9);const aim=new THREE.Vector3();
 try{renderer=new THREE.WebGLRenderer({canvas,alpha:true,antialias:true,powerPreference:'low-power'});renderer.setPixelRatio(Math.min(devicePixelRatio,1.5));renderer.setSize(innerWidth,innerHeight);scene=new THREE.Scene();camera=new THREE.PerspectiveCamera(55,innerWidth/innerHeight,.1,100);camera.position.copy(target);
  const n=reduce.matches?Math.max(70,Math.floor(count*.25)):count,pos=new Float32Array(n*3),col=new Float32Array(n*3);for(let i=0;i<n;i++){pos.set([(Math.random()-.5)*24,(Math.random()-.5)*18,(Math.random()-.5)*12],i*3);col.set([palette[0],palette[1]*(.35+Math.random()*.6),palette[2]*(.25+Math.random()*.7)],i*3);}const geo=new THREE.BufferGeometry();geo.setAttribute('position',new THREE.BufferAttribute(pos,3));geo.setAttribute('color',new THREE.BufferAttribute(col,3));stars=new THREE.Points(geo,new THREE.PointsMaterial({size:.065,vertexColors:true,transparent:true,opacity:.75,depthWrite:false}));scene.add(stars);
  ornaments=new THREE.Group();const coral=new THREE.MeshBasicMaterial({color:0xff754c,wireframe:true,transparent:true,opacity:.12}),amber=new THREE.MeshBasicMaterial({color:0xe7a64c,wireframe:true,transparent:true,opacity:.18});for(const [x,y,z,r,t,mat] of [[5.7,1.5,-2,1.75,.012,coral],[5.7,1.5,-2,1.25,.009,amber],[-5.6,-1.7,-3,1.25,.01,amber]]){const ring=new THREE.Mesh(new THREE.TorusGeometry(r,t,8,84),mat);ring.position.set(x,y,z);ring.rotation.set(.65,.2,Math.PI*.18);ornaments.add(ring);}const marker=new THREE.Mesh(new THREE.OctahedronGeometry(.32,0),coral);marker.position.set(-5.6,-1.7,-3);ornaments.add(marker);scene.add(ornaments);renderer.render(scene,camera);
 }catch(e){canvas.hidden=true;console.warn('WebGL no disponible; se conserva el fondo CSS.',e.message);}
 function resize(){if(!renderer)return;camera.aspect=innerWidth/innerHeight;camera.updateProjectionMatrix();renderer.setSize(innerWidth,innerHeight);}
 function tick(){frame=null;if(!renderer||document.hidden)return;if(!reduce.matches){stars.rotation.y+=.0007;stars.rotation.x+=.0002;ornaments.rotation.z+=.00035;ornaments.children.at(-1).rotation.y+=.008;camera.position.lerp(target,.035);camera.lookAt(aim);for(const item of bursts){item.life-=1;const a=item.geometry.attributes.position;for(let i=0;i<a.count;i++){a.array[i*3]+=item.vel[i*3];a.array[i*3+1]+=item.vel[i*3+1];a.array[i*3+2]+=item.vel[i*3+2];}a.needsUpdate=true;item.material.opacity=Math.max(0,item.life/35);if(item.life<=0){scene.remove(item);item.geometry.dispose();item.material.dispose();bursts.delete(item);}}}renderer.render(scene,camera);frame=requestAnimationFrame(tick);}
 function start(){if(renderer&&!reduce.matches&&!frame&&!document.hidden)frame=requestAnimationFrame(tick);}function setCamera(i){const p=cameras[i]||cameras[0]||[0,0,9];target.set(...p);if(reduce.matches){camera.position.copy(target);camera.lookAt(aim);renderer?.render(scene,camera);}else start();}
 function makeBurst(x=.5,y=.5){if(!renderer)return;const count=60,positions=new Float32Array(count*3),vel=new Float32Array(count*3);for(let i=0;i<count;i++){positions.set([(x-.5)*10,(.5-y)*7,0],i*3);const theta=Math.random()*Math.PI*2,speed=.025+Math.random()*.07;vel.set([Math.cos(theta)*speed,Math.sin(theta)*speed,(Math.random()-.5)*speed],i*3);}const geometry=new THREE.BufferGeometry();geometry.setAttribute('position',new THREE.BufferAttribute(positions,3));const material=new THREE.PointsMaterial({color:new THREE.Color(...palette),size:.12,transparent:true,opacity:1});const p=new THREE.Points(geometry,material);p.vel=vel;p.life=35;scene.add(p);bursts.add(p);start();}
 function dispose(){if(frame)cancelAnimationFrame(frame);removeEventListener('resize',resize);document.removeEventListener('visibilitychange',visibility);removeEventListener('pointermove',pointerMove);stars?.geometry.dispose();stars?.material.dispose();if(ornaments){scene.remove(ornaments);ornaments.children.forEach(o=>{o.geometry.dispose();o.material.dispose();});}for(const p of bursts){p.geometry.dispose();p.material.dispose();}renderer?.dispose();}
 function pointerMove(e){if(reduce.matches)return;aim.x=(e.clientX/innerWidth-.5)*.42;aim.y=-(e.clientY/innerHeight-.5)*.26;}
 function visibility(){if(document.hidden&&frame){cancelAnimationFrame(frame);frame=null;}else start();}
 addEventListener('resize',resize);addEventListener('pointermove',pointerMove,{passive:true});document.addEventListener('visibilitychange',visibility);active={makeBurst};return{setCamera,dispose,burst:makeBurst};
}
export function burst(x=.5,y=.5){active?.makeBurst(x,y);}
