import './style.css';
import '../shared-theme.css';
import {initBackground} from './background3d.js';
import {organizeAnalysisSlides} from '../presentation-layout.js';
import '../presentation.css';
const $=(q,root=document)=>root.querySelector(q);
const reduced=matchMedia('(prefers-reduced-motion: reduce)');
export function initPage({palette,count=420,cameras=[]}={}){
 const deck=$('#deck');organizeAnalysisSlides(document.body.dataset.page);
 const sections=[...deck.querySelectorAll(':scope > section')],bg=initBackground($('#universe'),{palette,count,cameras});let active=0;
 const pageTitles=location.pathname.endsWith('sensibilidad.html')?{inicio:'Reporte de sensibilidad del modelo de producción',laboratorio:'Laboratorio de reoptimización',curvas:'Ingreso óptimo según disponibilidad de recursos',decisiones:'Evaluación de escenarios y recomendaciones'}:{inicio:'Modelo de transporte de arroz',problema:'Formulación del modelo de transporte',construye:'Asignación de sacos por ruta',escenarios:'Simulador de tarifas',conclusiones:'Resultados y recomendaciones del modelo de transporte'};for(const section of sections){const title=pageTitles[section.id];if(title){const heading=section.querySelector(section.id==='inicio'?'h1':'h2');if(heading)heading.textContent=title;}}
 const brand=$('.topbar .brand');if(brand)brand.innerHTML='<span class="seal">Y</span> YARIMASHITA<span class="brand-sub">MAKI & RAMEN HOUSE</span>';
 const nav=$('.mobile-nav'),toggle=$('.menu-toggle');toggle?.addEventListener('click',()=>{const opened=toggle.getAttribute('aria-expanded')!=='true';toggle.setAttribute('aria-expanded',String(opened));nav.classList.toggle('open',opened);});
 const dots=document.createElement('nav');dots.className='progress';dots.setAttribute('aria-label','Progreso de la presentación');sections.forEach((section,i)=>{const b=document.createElement('button');b.setAttribute('aria-label',`Ir a la sección ${i+1}`);b.onclick=()=>section.scrollIntoView({behavior:reduced.matches?'instant':'smooth'});dots.append(b);});document.body.append(dots);
 const indicator=[...dots.children];const observer=new IntersectionObserver(entries=>entries.forEach(e=>{if(e.isIntersecting&&e.intersectionRatio>.5){active=sections.indexOf(e.target);indicator.forEach((d,i)=>d.classList.toggle('active',i===active));$('#prev').disabled=active===0;$('#next').disabled=active===sections.length-1;bg.setCamera(active);}}),{root:deck,threshold:[.5,.75]});sections.forEach(s=>observer.observe(s));
 const reveal=new IntersectionObserver(entries=>entries.forEach(e=>{if(e.isIntersecting){e.target.classList.add('visible');reveal.unobserve(e.target);}}),{root:deck,threshold:.12});deck.querySelectorAll('.reveal').forEach(e=>reveal.observe(e));
 const goto=i=>sections[Math.max(0,Math.min(sections.length-1,i))]?.scrollIntoView({behavior:reduced.matches?'instant':'smooth'});$('#prev').onclick=()=>goto(active-1);$('#next').onclick=()=>goto(active+1);
 document.addEventListener('keydown',e=>{if(/INPUT|SELECT|TEXTAREA|BUTTON/.test(document.activeElement.tagName))return;if(['ArrowDown','PageDown'].includes(e.key)){e.preventDefault();goto(active+1);}if(['ArrowUp','PageUp'].includes(e.key)){e.preventDefault();goto(active-1);}});
 const tooltip=document.createElement('div');tooltip.className='tooltip';tooltip.hidden=true;tooltip.role='tooltip';document.body.append(tooltip);let target;
 const glossary=location.pathname.endsWith('sensibilidad.html')?{'Costo reducido':'Cambio marginal en el ingreso óptimo al forzar una unidad de una variable que actualmente está en cero.','Rango permisible':'Intervalo del coeficiente en que la base óptima actual permanece sin cambios.','Precio sombra':'Cambio marginal del ingreso óptimo por una unidad adicional del recurso, válido dentro de su rango permisible.','holgura':'Cantidad de recurso disponible que queda sin utilizar en la solución óptima.','cuello de botella':'Recurso cuya disponibilidad limita mejorar el valor de la función objetivo.'}:{'problema balanceado':'Modelo en que la oferta total coincide con la demanda total.','ciclo':'Ruta cerrada de celdas alternadas que permite redistribuir sin cambiar oferta ni demanda.','óptimo alterno':'Plan diferente que alcanza exactamente el mismo costo mínimo.'};
 const terms=Object.keys(glossary);for(const el of deck.querySelectorAll('h2,h3,p,th,td,.badge,.callout')){const match=terms.find(t=>el.textContent.toLocaleLowerCase().includes(t.toLocaleLowerCase()));if(match){el.classList.add('tooltip-term');el.tabIndex=0;el.dataset.glossary=glossary[match];}}
 function show(el){if(!el)return;target=el;tooltip.textContent=el.dataset.glossary;tooltip.hidden=false;el.setAttribute('aria-describedby','glossary-tip');tooltip.id='glossary-tip';const r=el.getBoundingClientRect();tooltip.style.left=`${Math.min(innerWidth-tooltip.offsetWidth-12,Math.max(12,r.left))}px`;tooltip.style.top=`${Math.max(12,r.top-tooltip.offsetHeight-9)}px`;}
 function hide(){target?.removeAttribute('aria-describedby');target=null;tooltip.hidden=true;}
 document.addEventListener('pointerover',e=>{const el=e.target.closest('[data-glossary]');if(el)show(el);});document.addEventListener('pointerout',e=>{if(target&&!target.contains(e.relatedTarget))hide();});document.addEventListener('focusin',e=>show(e.target.closest('[data-glossary]')));document.addEventListener('focusout',hide);document.addEventListener('click',e=>{const term=e.target.closest('[data-glossary]');if(term)show(term);else if(!e.target.closest('.mobile-nav'))hide();});deck.addEventListener('scroll',hide,{passive:true});document.addEventListener('keydown',e=>{if(e.key==='Escape')hide();});
 document.addEventListener('click',e=>{const link=e.target.closest('a[href]');if(!link)return;const href=link.getAttribute('href');if(href.startsWith('#')){const node=$(href);if(node){e.preventDefault();node.scrollIntoView({behavior:reduced.matches?'instant':'smooth'});}return;}if(/\.html(?:$|#)/.test(href)&&!e.ctrlKey&&!e.metaKey){e.preventDefault();document.body.classList.add('fade-out');setTimeout(()=>location.href=href,300);}});
 const here=location.pathname.split('/').pop()||'index.html';document.querySelectorAll('[data-page-link],.mobile-nav a').forEach(a=>{if(a.getAttribute('href').split('/').pop()===here)a.setAttribute('aria-current','page');});
 if(location.hash){const target=document.getElementById(decodeURIComponent(location.hash.slice(1)));if(target&&deck.contains(target))requestAnimationFrame(()=>target.scrollIntoView({behavior:'instant'}));}
 addEventListener('pagehide',()=>{observer.disconnect();reveal.disconnect();bg.dispose();});
 if(new URLSearchParams(location.search).get('debug')==='1')void import('./selftest.js').then(m=>m.runSelftest());
 return{sections,go:goto,bg};
}
