import {products,prices,baseMix,resources,demand,transport,transportCost} from './data.js';
import {solveLP} from './lp.js';
const near=(a,b,t=.015)=>Number.isFinite(a)&&Math.abs(a-b)<=t;
function prod(overrides={}){const p=[...prices],caps=resources.map(r=>r.cap),mins=demand.map(d=>d.value);for(const[i,v]of overrides.prices||[])p[i]=v;for(const[i,v]of overrides.caps||[])caps[i]=v;for(const[i,v]of overrides.mins||[])mins[i]=v;const cons=[...resources.map((r,i)=>({a:r.a,b:caps[i],sense:'<='})),...mins.map((v,i)=>({a:products.map((_,j)=>j===demand[i].index?-1:0),b:-v,sense:'<='}))];return solveLP({objective:p,constraints:cons});}
function trans(costs=transport.costs){const c=costs.flat(),constraints=[];transport.suppliers.forEach((s,i)=>constraints.push({a:c.map((_,k)=>Math.floor(k/3)===i?1:0),b:s.supply,sense:'='}));transport.stores.forEach((s,j)=>constraints.push({a:c.map((_,k)=>k%3===j?1:0),b:s.demand,sense:'='}));return solveLP({objective:c,constraints,sense:'min'});}
function matrixPlan(r){return Array.from({length:3},(_,i)=>Array.from({length:3},(_,j)=>r.x[i*3+j]));}
function minCostPlan(){const left=transport.suppliers.map(s=>s.supply),need=transport.stores.map(s=>s.demand),plan=Array.from({length:3},()=>[0,0,0]);while(need.some(v=>v>0)){let best=null;for(let i=0;i<3;i++)for(let j=0;j<3;j++)if(left[i]>0&&need[j]>0){const amount=Math.min(left[i],need[j]),cand={i,j,amount,cost:transport.costs[i][j]};if(!best||cand.cost<best.cost-1e-9||(Math.abs(cand.cost-best.cost)<1e-9&&cand.amount>best.amount))best=cand;}plan[best.i][best.j]=best.amount;left[best.i]-=best.amount;need[best.j]-=best.amount;}return plan;}
export function runSelftest(){
 const checks=[],add=(name,expected,actual,pass)=>checks.push({name,expected,actual,pass});const result=(label,r,z)=>add(label,z,r.z,near(r.z,z));
 const base=prod();result('Producción base Z',base,1057);add('Vector base X',(baseMix).join(', '),base.x.map(v=>+v.toFixed(3)).join(', '),base.x.every((v,i)=>near(v,baseMix[i],.015)));
 let r=prod({prices:[[3,28]]});add('Salmón S/28 conserva mezcla base','misma mezcla',r.x.map(v=>+v.toFixed(3)).join(', '),r.x.every((v,i)=>near(v,baseMix[i],.015)));r=prod({prices:[[1,25]]});add('California S/25 conserva mezcla base','misma mezcla',r.x.map(v=>+v.toFixed(3)).join(', '),r.x.every((v,i)=>near(v,baseMix[i],.015)));
 r=prod({prices:[[3,27.9]]});result('Salmón S/27.90',r,1033);add('Tokyo Roll entra a 12',12,r.x[4],near(r.x[4],12));add('Salmón sale',0,r.x[3],near(r.x[3],0));
 r=prod({prices:[[1,26.5]]});result('California S/26.50',r,1061.75);add('California 9.5',9.5,r.x[1],near(r.x[1],9.5));add('Salmón 2.5',2.5,r.x[3],near(r.x[3],2.5));
 r=prod({prices:[[0,27]]});result('Acevichado S/27',r,1091.5);add('Acevichado 14.5',14.5,r.x[0],near(r.x[0],14.5));
 r=prod({prices:[[5,20]]});result('Ramen Especial S/20',r,933.103);add('Ramen Clásico 18.69',18.69,r.x[6],near(r.x[6],18.69));
 r=prod({prices:[[5,38]]});result('Ramen Especial S/38',r,1180.833);add('Ramen Especial a 16.667',16.667,r.x[5],near(r.x[5],16.667));add('Salmón a 10.417',10.417,r.x[3],near(r.x[3],10.417));r=prod({prices:[[6,21]]});result('Ramen Clásico S/21',r,1075.241);add('Ramen Clásico a 18.69',18.69,r.x[6],near(r.x[6],18.69));
 for(const[cap,z,name]of [[519,1095,'Tiempo 519'],[600,1216.109,'Tiempo 600'],[400,857,'Tiempo 400']])result(name,prod({caps:[[8,cap]]}),z);
 for(const[cap,z,name]of [[5104.17,1047.5,'Arroz 5104.17'],[5833.33,1065,'Arroz 5833.33'],[6500,1065,'Arroz 6500']]){r=prod({caps:[[1,cap]]});result(name,r,z);if(cap===6500){add('Arroz 6500 · Salmón 13.333',13.333,r.x[3],near(r.x[3],13.333));add('Arroz 6500 · Ramen Especial 14.333',14.333,r.x[5],near(r.x[5],14.333));}}
 const baseT=trans();result('Transporte base óptimo',baseT,35);add('Costo plan Excel',35.5,transportCost(transport.plans.excel),near(transportCost(transport.plans.excel),35.5));const greedy=minCostPlan();add('Costo método mínimo',36,transportCost(greedy),near(transportCost(greedy),36));
 const delta=(plan,route,cycle)=>cycle.reduce((v,edge,k)=>v+(k%2===0?1:-1)*transport.costs[edge[0]][edge[1]],0);const minCycle={macroChilca:[[0,1],[0,0],[1,0],[1,1]],masChilca:[[2,1],[2,0],[1,0],[1,1]],metroGrau:[[1,2],[1,0],[0,0],[0,2]],masGrau:[[2,2],[2,0],[0,0],[0,2]]};for(const[name,cycle,expected]of [['Δ Mac-Chilca',minCycle.macroChilca,5.5],['Δ Mas-Chilca',minCycle.masChilca,5.5],['Δ Metro-Grau',minCycle.metroGrau,-.5],['Δ Mas-Grau',minCycle.masGrau,0]])add(name,expected,delta(null,null,cycle),near(expected,delta(null,null,cycle)));
 const costs=transport.costs.map(a=>[...a]);for(const[i,j,v,z,name]of [[1,1,3,47.5,'Metro-Chilca tarifa 3'],[0,0,1,19,'Macro-Tambo tarifa 1'],[1,0,2,28,'Metro-Tambo tarifa 2'],[0,2,3,35,'Macro-Grau tarifa 3']]){const c=costs.map(a=>[...a]);c[i][j]=v;result(name,trans(c),z);}
 const panel=document.createElement('aside');panel.id='acceptance-tests';panel.className='card';panel.style.cssText='position:fixed;z-index:200;right:14px;top:90px;width:min(440px,calc(100vw - 28px));max-height:78vh;overflow:auto;background:#171614f5';panel.innerHTML=`<button id="close-tests" class="button" style="float:right">Cerrar</button><h2 style="font:28px Bebas">Pruebas de aceptación · ${checks.filter(c=>c.pass).length}/${checks.length}</h2>${checks.map(c=>`<p style="padding:8px;border-bottom:1px solid #ffffff20;color:${c.pass?'#8de0c5':'#ff8876'}">${c.pass?'✓':'✗'} ${c.name}<small style="display:block;color:#aaa">Esperado: ${c.expected} · Obtenido: ${typeof c.actual==='number'?Number(c.actual.toFixed(4)):c.actual}</small></p>`).join('')}`;document.body.append(panel);panel.querySelector('#close-tests').onclick=()=>panel.remove();console.table(checks);console.info(`Autoevaluación: ${checks.filter(c=>c.pass).length}/${checks.length} pruebas aprobadas.`);
}
